name: reeve

on:
  pull_request:
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write
  issues: write
  id-token: write

concurrency:
  group: reeve-${{ github.event.pull_request.number || github.event.issue.number }}

jobs:
  reeve:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: FynxLabs/reeve@master
        with:
          pulumi-version: latest
          slack-token: ${{ secrets.SLACK_BOT_TOKEN }}
