name: reeve

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write
  issues: write
  id-token: write        # OIDC federation

concurrency:
  group: reeve-${{ github.event.pull_request.number || github.event.issue.number }}
  cancel-in-progress: false

jobs:
  preview:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: FynxLabs/reeve@main
        with:
          command: preview
          pulumi-version: "3.231.0"

  apply:
    if: |
      github.event_name == 'issue_comment' &&
      github.event.issue.pull_request &&
      startsWith(github.event.comment.body, '/reeve apply')
    runs-on: ubuntu-latest
    steps:
      - name: Resolve PR head ref
        id: pr
        uses: actions/github-script@v9
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });
            core.setOutput('ref', pr.data.head.sha);
      - uses: actions/checkout@v6
        with:
          ref: ${{ steps.pr.outputs.ref }}
      - uses: FynxLabs/reeve@main
        with:
          command: apply
          pulumi-version: "3.231.0"
